# ICRP Publ.141 p.235 Para.564 / アクチニド子孫元素としてのフランシウムおよびアスタチン
# > (564) Radioisotopes of francium and astatine appearing in actinide chains considered
# > in this publication have short half-lives, and are assumed to decay at their site
# > of production in systemic tissues or blood.
# > (564) 本書で検討されるアクチニド壊変系列に現れるフランシウムおよびアスタチンの
# > 放射性同位体は半減期が短く、全身組織または血液中の生成部位において崩壊すると仮定されます。

[{At}:compartment]

[{At}:transfer]
