[parameter]

  ${Ga}/Blood = 'Blood'
  ${Zn}/Blood = 'Plasma'
  ${Cu}/Blood = 'Plasma'

  ${Ga}/fA_MaxValueOfIng = 0.001        # ICRP Publ.151 p.162 Table 17.2 / Ingested materials, All forms
  ${Zn}/fA_MaxValueOfIng = 0.5          # ICRP Publ.134 p.186 Table  9.2 / Ingested materials, All forms
  ${Cu}/fA_MaxValueOfIng = 0.5          # ICRP Publ.151 p.153 Table 16.2 / Ingested materials, All forms
