[parameter]
  ${Ba,Cs}/Blood = 'Plasma'

  ${Ba}/fA_MaxValueOfIng = 0.2          # ICRP Publ.137 p.168 Table 7.2 / Ingested materials, Soluble forms
  ${Cs}/fA_MaxValueOfIng = 0.99 # ≒1   # ICRP Publ.137 p.142 Table 6.2 / Ingested materials, All unspecified compounds
  ${Xe}/fA_MaxValueOfIng = 0            # ICRP Publ.130 p.45 Para.38
  ${I}/fA_MaxValueOfIng = 0.99 # ≒1    # ICRP Publ.137 p.97  Table 5.3 / Ingested materials, All unspecified forms
