[{At}:compartment]
[{At}:transfer]

#    ICRP Publ.137 p.370 Para.812 / トリウム系列子孫元素としてのフランシウムおよびアスタチンは、ラジウム子孫元素としてのモデルを用いる。
# → ICRP Publ.137 p.334 Para.717 / ラジウム子孫元素としてのフランシウムおよびアスタチン
# > (717) Radioisotopes of francium and astatine appearing in radium chains considered
# > in this publication have half-lives varying from less than 1 s to 22 min.
# > These short-lived radionuclides are assumed to decay at their sites of production in
# > systemic tissues and fluids.
# > (717) 本書で取り上げているラジウムの崩壊系列に現れるフランシウムおよびアスタチンの
# > 放射性同位体は、1秒未満から22分という範囲の半減期を有している。これらの短寿命
# > 放射性核種は、全身の組織や体液中の生成部位において崩壊すると仮定されている。
