[parameter]

  ${Co}/Blood = 'Blood1'
  ${Fe}/Blood = 'OtherPlasma'
  ${Mn}/Blood = 'Plasma'

  ${Co}/fA_MaxValueOfIng = 0.1          # ICRP Publ.134 p.156 Table  8.2 / Ingested materials, All chemical forms
  ${Fe}/fA_MaxValueOfIng = 0.1          # ICRP Publ.134 p.136 Table  7.2 / Ingested materials, All unspecified forms
  ${Mn}/fA_MaxValueOfIng = 0.05         # ICRP Publ.151 p.119 Table 14.2 / Ingested materials, All forms
