[parameter]

  ${Nb,Zr,Y}/Blood = 'Blood1'
  ${Sr}/Blood = 'Blood'

  ${Nb}/fA_MaxValueOfIng = 0.01         # ICRP Publ.134 p.288 Table 13.2 / Ingested materials, All forms
  ${Zr}/fA_MaxValueOfIng = 0.002        # ICRP Publ.134 p.264 Table 12.2 / Ingested materials, All chemical forms
  ${Y}/fA_MaxValueOfIng = 1E-4          # ICRP Publ.134 p.242 Table 11.2 / Ingested materials, All chemical forms
  ${Sr}/fA_MaxValueOfIng = 0.25         # ICRP Publ.134 p.215 Table 10.2 / Ingested materials, All other chemical forms
