[parameter]

  ${Y}/Blood     = 'Blood1'
  ${Sr,Kr}/Blood = 'Blood'
  ${Rb}/Blood    = 'Plasma'

  ${Y}/fA_MaxValueOfIng = 1E-4          # ICRP Publ.134 p.242 Table 11.2 / Ingested materials, All chemical forms
  ${Sr}/fA_MaxValueOfIng = 0.25         # ICRP Publ.134 p.215 Table 10.2 / Ingested materials, All other chemical forms
  ${Rb}/fA_MaxValueOfIng = 0.99 # ≒1   # ICRP Publ.151 p.202 Table 22.2 / Ingested materials, All forms
  ${Kr}/fA_MaxValueOfIng = 0            # ICRP Publ.130 p.45 Para.38
